# It contains all the configs required in the project

  ARTIFACTS_DIR: artifacts
artifacts:
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: init_model.h5
  UPDATED_BASE_MODEL_NAME: updated_base_model.h5
  TRAINED_MODEL_NAME: trained_model.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: "logs"
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks

data:
  source_url: "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_3367a.zip"
  local_dir: data
  data_file: data.zip
  unzip_data_dir: data
  bad_data_dir: bad_data
  parent_data_dir: PetImages