# It contains all the configs required in the project

  ARTIFACTS_DIR: artifacts
artifacts:
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: init_model.h5
  UPDATED_BASE_MODEL_NAME: updated_base_model.h5
  TRAINED_MODEL_NAME: trained_model.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: "logs"
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks
  CB_BYTECODE_FNAME : callbacks_lst.pickel

data:
  source_url: "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_3367a.zip"
  local_dir: data
  data_file: data.zip
  unzip_data_dir: data
  bad_data_dir: bad_data
  parent_data_dir: PetImages


params:
  img_shape: [180,180,3]
  lr : 0.001 # Learning rate
  loss: sparse_categorical_crossentropy
  metrics: ["accuracy"]
  validation_split : 0.2
  batch_size : 32
  seed : 42
  buffer_size: 32
  epochs: 1

callbacks:
  list: ["ModelCheckpoint","customCallback"]
  ModelCheckpoint:
    filename : "model_ckpt.h5"
    save_best_only : True
    save_weights_only : False
  customCallback:
    ACCURACY_THRESHOLD : 0.95
  
  
